In [12]:
import numpy as np
import numpy.random as npr
from scipy.stats import mode

In [25]:
for i in range(20):
    x = npr.randint(1,6, size=5)
    if x.mean() == np.round(x.mean()):
        print(x)
        print('\t', x.mean())
        print('\t', np.median(x))
        print('\t', mode(x))
        print()


[4 5 3 4 4]
	 4.0
	 4.0
	 ModeResult(mode=4, count=3)

[2 2 4 1 1]
	 2.0
	 2.0
	 ModeResult(mode=1, count=2)

[1 5 4 2 3]
	 3.0
	 3.0
	 ModeResult(mode=1, count=1)

[3 4 4 4 5]
	 4.0
	 4.0
	 ModeResult(mode=4, count=3)

[4 2 3 4 2]
	 3.0
	 3.0
	 ModeResult(mode=2, count=2)

[1 3 5 2 4]
	 3.0
	 3.0
	 ModeResult(mode=1, count=1)

[2 2 1 1 4]
	 2.0
	 2.0
	 ModeResult(mode=1, count=2)

[5 2 3 3 2]
	 3.0
	 3.0
	 ModeResult(mode=2, count=2)

[1 4 2 4 4]
	 3.0
	 4.0
	 ModeResult(mode=4, count=3)



In [27]:
for i in range(20):
    x = npr.randint(1,8, size=5)
    if x.mean() == np.round(x.mean()):
        print(x)
        print('\t', x.mean())
        print('\t', np.median(x))
        print('\t', mode(x))
        print()


[1 1 5 1 2]
	 2.0
	 1.0
	 ModeResult(mode=1, count=3)

[3 7 3 2 5]
	 4.0
	 3.0
	 ModeResult(mode=3, count=2)

[4 1 2 7 1]
	 3.0
	 2.0
	 ModeResult(mode=1, count=2)



In [23]:
for i in range(20):
    x = npr.randint(1,10, size=6)
    if x.mean() == np.round(x.mean()):
        print(x)
        print('\t', x.mean())
        print('\t', np.median(x))
        print('\t', mode(x))
        print()


[6 8 8 2 6 6]
	 6.0
	 6.0
	 ModeResult(mode=6, count=3)

[5 8 5 8 3 7]
	 6.0
	 6.0
	 ModeResult(mode=5, count=2)



In [24]:
for i in range(20):
    x = npr.randint(1,10, size=6)
    if x.mean() == np.round(x.mean()):
        print(x)
        print('\t', x.mean())
        print('\t', np.median(x))
        print('\t', mode(x))
        print()


[1 4 2 1 7 3]
	 3.0
	 2.5
	 ModeResult(mode=1, count=2)

[5 2 8 1 5 9]
	 5.0
	 5.0
	 ModeResult(mode=5, count=2)

[8 5 2 3 1 5]
	 4.0
	 4.0
	 ModeResult(mode=5, count=2)

[3 5 7 3 3 3]
	 4.0
	 3.0
	 ModeResult(mode=3, count=4)

[1 3 1 2 2 9]
	 3.0
	 2.0
	 ModeResult(mode=1, count=2)

